author: zlc1994 # 作者
description:
keyword:
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 #Projects: /project/
 #About: /about/

# highlight
highlight:
  tomorrow

# gitment
#gitment_owner: yanm1ng
#gitment_repo: yanm1ng.github.io
#gitment_oauth_id: 0f87e490e00ee3fd87ef
#gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: 
  avatar: 
  description:
